### ISSUE TITLE
More useful information

### ISSUE THREAD

**Issue by ifohancroft** [perigoso/g305-re#1]
Here is some more information, that I find is helpful when trying to reverse engineer a mouse, that isn't present in the README:

Frequency range: 2.402-2.481 GHz (While the antena itself is capable of 2.4 to 2.4835GHz and the antena type is Ceramic chip Antenna)

Endianness of the MCU: Little Endian
The MCU is ARM Cortex M4 (the README does mention it's ARM but it doesn't mention that it's Cortex and which one, while the information can be found by looking for the datasheet for the MCU it's helpful to have it in the README).

Modulation Technology: GFSK

FCC Documents: https://fccid.io/JNZMR0071

I can't find information for the dongle because I can't find its FCC documents because I can't find its product number or FCC ID and the dongle shown in the FCC documents is for the G603 and I don't know if it comes with it or it whether the mouse has its own.

It would be useful if someone can provide USB captures in pcapng format of a firmware update of the mouse (even more useful if captures of the firmware update for two consecutive versions can be provided), as well as the update binaries.

**Comment by perigoso** [comment]
Thank you, I will add this to the readme

**Comment by ifohancroft** [comment]
Most welcome!

Unfortunately, I do not own the mouse. If you do, can you please tell me the following so I can hopefully dig up more information:
The dongle that it comes with - does it say G305 on it or does it actually say G603 like on the FCC internal photos? If the G305 does have its own dongle - what's its FCC ID or Model/Product Number (should be written on the dongle somewhere)?

It's worth checking out because there is a chance the dongle itself uses a different version or model MCU. For example, on my Viper Ultimate, it turned out that the mouse uses nRF52840, while the dongle uses nRF52810.

Btw, the idea of looking at the hardware side and not just the firmware, and actually overlaying the traces on top of the PCB in GIMP and labeling the pins and functions is brilliant! Kudos!

**Comment by perigoso** [comment]
I think logitech uses the same dongles for a bunch of products, but I will check it when I can.
I also believe they have a couple different compatible dongles, that even use different brand mcus, like a TI, but I not 100% on this, anyway I doubt its the same mcu.

**Comment by ifohancroft** [comment]
You never know :D My mouse's dongle actually uses the 810 but I am guessing they are using it just for the wireless and the USB itself is either external controller or a separate chip (or implemented in pure software but I doubt it).

Do let me know the number on it when you have a chance to check it out though.

**Comment by perigoso** [comment]
@ifohancroft 
![IMG_20210514_230110](https://user-images.githubusercontent.com/39195157/118336177-0f3e3400-b509-11eb-89c0-e745211a90cf.jpg)
![IMG_20210514_230056](https://user-images.githubusercontent.com/39195157/118336179-106f6100-b509-11eb-82f7-86345f890d8f.jpg)

**Comment by perigoso** [comment]
Just like I said the receiver uses a TI chip, the CC2544

**Comment by ifohancroft** [comment]
Thank you!

**Comment by ifohancroft** [comment]
Here's more info about the receiver. Might be worth adding as well:

FCC Documents: https://fccid.io/JNZCU0008A
Frequencies: 2.402 to 2.481GHz
Modulations technology: GFSK
Antenna Type: Printed
MCU: TI CC2544

**Comment by perigoso** [comment]
Merged this new info into the readme

**Comment by ifohancroft** [comment]
@perigoso Sorry, I forgot to mention something important: Limited Results has recommended to me the ultimate version of the PocketGlitcher https://www.tindie.com/products/limitedresults/pocketglitcher/ as a tool-less and non-destructive way to circumvent APPROTECT and extract the firmware from nRF52* without the needing to open the device, solder to it, remove caps, etc.

However, the documentation needs to be read as I am not sure whether another tool isn't also required and what is the exact operating procedure.

**Comment by perigoso** [comment]
thank, Ill be trying the hard way first though

**Comment by ifohancroft** [comment]
Same :D
