### ISSUE TITLE
flashing firmware

### ISSUE THREAD

**Issue by ksoju** [perigoso/g305-re#4]
I'm guessing that you're dumping/flashing the from the MCU firmware via some JTAG onto the test points possibly. Can you provide more information for us new to hardware on how to do this? From what i gather, SWDIO and SWCLK should be the ones (maybe there are more) and I'd need to solder wires to them and hook a programmer/debugger to dump/flash. Any specific tools maybe that'll make this process more seamless? Any pointers would be much appreciated. Thanks!

**Comment by perigoso** [comment]
If you're just looking to play with the firmware we have dumped a couple you have access to in the repo.

As for dumping it yourself you're gonna some sort of arm capable programmer, i personally use a jlink clone. The debug protocol is "swd" (a form of jtag particular for arm processors).
The typical connections needed are:
TP10 - GND
TP11- VDD
TP12 - SWDIO
TP13 - SWCLK
TP14 - RESET
All test points are labeled and were reversed, there's a table in the readme. This particular set is on the front right of the pcb, next to the scroll wheel.

Good luck.

If you need anything do ask.

**Comment by ksoju** [comment]
Thanks, this is awesome to know this. Might be something useful to put in the readme. I'm thinking of trying out something like q305 project by qsxcv but not the 8k polling but I will definitely peruse the firmware to see what can be tweaked.
